include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    file_names: ignore
    constant_identifier_names: ignore
    library_private_types_in_public_api: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    camel_case_types: ignore
    use_build_context_synchronously: ignore
    unused_field: ignore
    curly_braces_in_flow_control_structures: ignore
    prefer_typing_uninitialized_variables: ignore
    unused_local_variable: ignore
    unused_element: ignore
    depend_on_referenced_packages: ignore
